.env.example
CHANGELOG.md
Dockerfile
README.md
docker-compose.yml

- JIRA ticket [DR-2446](https://jira.nypl.org/browse/DR-2446)
- Added Dockerfile and docker-compose.yml files.
- Creates initial Docker support for the application.
- Adds Docker documentation to Readme
- Creates .env.example file
- by running `docker-compose build` and `docker-compose up` locally and going to http://localhost:3000/. 
-
- [x ] I have added relevant accessibility documentation for this pull request.
- [ x] All new and existing tests passed.

Dr 2446 dockerize application

---

.travis.yml
CHANGELOG.md

I used a modified version of this script to push the `DR-2448-setup-travis-latest` image you can see in ECR. I also used another modified version to push `qa-latest` and could see that the QA cluster tasks updated correctly. However, the full test of this script will only happen when it is merged to qa.

DR-2448 setup travis

---

.travis.yml

WIP. Building and pushing the image to ECR works, but the infrastructure doesn't exist yet to test the task updates.

DR-2564 travis script for production deployment

---

.travis.yml

This fixes the production branch deployment from the temporary pull request branch **DR-2564-production-travis** to the **production** branch.
This also combines deployments on QA and production into a single travis task each, rather than two.

DR-2564 simplify travis script and fix production branch

---

package-lock.json
package.json
src/components/swimlanes/swimLanes.tsx

Fixes JIRA ticket [DR-2588](https://jira.nypl.org/browse/DR-2588)
- Fixes hydration error with `<p>` rendering within a `<p>` in card subtitles

Corrected subtitle behavior in DR-2588

---

src/components/header/header.tsx
src/components/logo/logo.tsx
src/components/search/search.tsx
src/utils/breakpoints.ts

Fixes JIRA tickets [DR-2586](https://jira.nypl.org/browse/DR-2586) and [DR-2648](https://jira.nypl.org/browse/DR-2648).
- Changes breakpoints on search bar 
- See https://github.com/NYPL/digital-collections/pull/36 for previous work on search bar/filter

DR-2586 and DR-2648 Redesigned search bar with filter

---

CHANGELOG.md
src/pages/_document.tsx

- JIRA ticket [DR-2591](https://jira.nypl.org/browse/DR-2591)
- Adds global footer component to homepage
- curious what/where the best way to test this is (homepage.test.tsx or create a new file ie. _document.test.txs?)
-

DR-2591 implement Footer component 

---

log/dc.log
src/components/exploreFurther/exploreFurther.tsx
src/components/hero/campaignHero.tsx
src/components/swimlanes/swimLanes.tsx

- JIRA ticket [DR-2711](https://jira.nypl.org/browse/DR-2711)
- Removes overrides for link color
- Corrects subtitle text for swimlanes
- Adds dark overlay to hero component
Locally

DR-2711: Confirm global footer and styling fixes

---

src/pages/_app.tsx

Fixes JIRA ticket [DR-2741](https://jira.nypl.org/browse/DR-2741).
- Adds a couple missing meta tags
Locally

DR-2741: Meta tags QA additions

---

vercel.json

- No ticket
- Based on work Diego did in Research Catalog.
- Adds a Vercel config to extend the timeout.
- Just a minor patch as this does not affect AWS.
On the Vercel preview by making incognito or hard refresh requests. Does this seem to reduce the 504 issue only on Vercel?
- N/A

NO_REF: Adding vercel config - 504 debugging

---

src/pages/_app.tsx
src/utils/utils.ts

log environment variables used in Adobe Analytics implementation

add logs for adobe env variables

---

CHANGELOG.md
src/pages/_app.tsx

- JIRA ticket [DR-2744](https://jira.nypl.org/browse/DR-2744)
-adds optinmonster embed code to _app.tsx
- qa-new-digitalcollections.nypl.org needs to be whitelisted to use optinmonster. Lana is working on this - Looks like we're ready to go.
-

DR-2744/implement optinmonster

---

.travis.yml
Dockerfile
appConfig.ts

declare APP_ENV with docker build in travis.yml and in Dockerfile

create env var for APP_ENV on build

---

CHANGELOG.md
src/pages/_app.tsx

- JIRA ticket [DR-2784](https://jira.nypl.org/browse/DR-2784)
- Adds a canonical link to the html HEAD element
I ran the app locally and saw the tag appears as expected

DR-2784 add canonical link

---

.travis.yml

remove second --build-arg for qa build in .travis.yml

---

.travis.yml

made changes to travis file following this thread: https://nypl.slack.com/archives/C1Q09LFAR/p1709306555084709

update travis file to use ruby

---

.github/workflows/swimlanes_test.yml
.gitignore

Fixing a typo in https://github.com/NYPL/digital-collections/pull/108

DR 2912 enable GitHub actions for swimlanes test v2

---

package.json

More typos related to https://github.com/NYPL/digital-collections/pull/108

DR 2912 enable GitHub actions for swimlanes test v3

---

src/components/featuredContent/featuredContent.test.tsx
src/components/featuredContent/featuredContent.tsx
src/components/header/header.tsx
src/components/hero/campaignHeroSubText.tsx
src/pages/_document.tsx
src/pages/index.tsx

Resolves ticket [DR-2894](https://jira.nypl.org/browse/DR-2894).
- Fixes focus outline on hero link
- Removes confusing alt text from FeaturedContent link and image
- Adds SkipNav to header
- These fixes are just to improve accessibility, no visual or functional changes

DR-2894: Quick pre-launch a11y fixes

---

src/data/aboutPageElements.tsx

Resolves JIRA ticket [DR-2807](https://jira.nypl.org/browse/DR-2807)
- Corrects text from QA
Locally

DR-2807: QA About page

---

README.md

Resolves JIRA ticket [DR-2868](https://jira.nypl.org/browse/DR-2868).
- Adds basic Next.js info to README for devs fresh from legacy RoR app

DR-2868: Adding section on Next.js to README

---

src/pages/api/feedback.ts

https://jira.nypl.org/browse/DR-2918
The application is experiencing an error when submitting an entry to Google sheets. This will just allow the details of the error to be seen in a console.

DR-2918 return error message upon google sheet submission error

---

CHANGELOG.md
src/pages/_app.tsx

- JIRA ticket [[DR-2918](https://jira.nypl.org/browse/DR-2918)
- comments out the feedback button. we'll fix it after launch.
- locally or in the vercel preview.

DR-2918 comment out feedback button

---

src/data/aboutPageElements.tsx

Resolves JIRA ticket [DR-2972](https://jira.nypl.org/browse/DR-2972)
- Adds paragraph break to Platform section of About page

DR-2972: QA fix paragraph break About page

---

src/components/swimlanes/swimLanes.tsx
src/pages/_app.tsx
src/pages/_document.tsx

- JIRA ticket [DR-2891](https://jira.nypl.org/browse/DR-2891)
- test optinmonster fix
-

optinmonster

---

jest.setup.ts
package-lock.json
src/components/exploreFurther/exploreFurther.tsx
src/components/hero/campaignHeroSubText.tsx
src/components/swimlanes/swimLanes.tsx
src/components/swimlanes/swimlanes.test.tsx
src/hooks/useBreakpoints.ts
tsconfig.json

- JIRA ticket [DR-2695](https://newyorkpubliclibrary.atlassian.net/browse/DR-2695)
- Adds tool tips to swim lane card titles and the hero's featured image link
- Adds `useBreakpoints` hook with new breakpoints (DS will incorporate soon)
Locally

DR-2695: Tool tips on home page

---

app/api/homepage/route.tsx
app/components/homePageMainContent/homePageMainContent.tsx
app/utils/utils.ts

Adding log of swim lanes data

---

CHANGELOG.md
__tests__/data/homepageProps.tsx
app/components/homePageMainContent/homePageMainContent.tsx
app/components/swimlanes/Swimlanes.module.css
app/components/swimlanes/swimLanes.tsx

Resolves JIRA ticket [DR-3036](https://newyorkpubliclibrary.atlassian.net/browse/DR-3036)
- Adds new column breakpoints to the home page swimlanes

DR-3036: Card column breakpoints

---

CHANGELOG.md
app/collections/[slug]/page.tsx
app/collections/lane/[slug]/page.tsx
app/collections/page.tsx
app/divisions/[slug]/page.tsx
app/divisions/page.tsx
package-lock.json
package.json
src/components/pageLayout/pageLayout.tsx
src/components/search/search.tsx

- JIRA ticket [DR-3023](https://newyorkpubliclibrary.atlassian.net/browse/DR-3023)
- Renders static breadcrumbs
[DR-3023]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DR-3023: Render static breadcrumbs

---

CHANGELOG.md
app/divisions/page.tsx
package-lock.json
package.json
src/components/homePageMainContent/homePageMainContent.tsx
src/components/pageLayout/pageLayout.tsx
src/components/pages/divisionsPage/divisionsPage.tsx
src/hooks/useNumColumns.ts

- JIRA ticket [DR-3030](https://newyorkpubliclibrary.atlassian.net/browse/DR-3030)
- Creates page component for All Divisions page (dummy data/ mainly scaffolding)
- Updates DS to `3.2.0`
[DR-3030]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DR-3030: Render All Divisions page

---

CHANGELOG.md
app/src/components/collectionLanes/collectionLanes.tsx
app/src/components/pages/divisionsPage/divisionsPage.tsx
package-lock.json
package.json

Resolves JIRA ticket [DR-3101](https://newyorkpubliclibrary.atlassian.net/browse/DR-3101)
- Adjusts lane title widths and link behavior to better handle long titles
- Also updates DS to `v3.3.2`
[DR-3101]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DR-3101 (continued): VQA on Divisions page

---

CHANGELOG.md
app/src/components/card/card.tsx
app/src/components/exploreFurther/exploreFurther.tsx
app/src/components/grids/cardsGrid.tsx
app/src/components/lane/lane.tsx
app/src/data/exploreFurtherData.ts
app/src/types/ExploreFurtherDataType.ts

Release v0.1.16-alpha

---

CHANGELOG.md
newrelic.js
next.config.js
public/CHANGELOG.md

- JIRA ticket [DR-3161](https://newyorkpubliclibrary.atlassian.net/browse/DR-3261)
- Sets NR to its default settings to capture and send transactions.
- Using `newrelic` package over `@newrelic/next` in the next.js config.
- Still testing this out.
-
[DR-3161]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DR-3161: New Relic transaction captures

---

app/divisions/[slug]/page.tsx
app/src/components/card/cardImage.tsx

- JIRA ticket [xxx](url)
- adds placeholder to thumbnails for divisions landing page
-
-

No ref/fix loading states for pagination

---

CHANGELOG.md
appConfig.ts
package.json
public/CHANGELOG.md

- JIRA ticket [DR-3298](https://newyorkpubliclibrary.atlassian.net/browse/DR-3298)
Will backmerge to qa and main
[DR-3298]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Hotfix/dr 3298/update prod dc url

---

CHANGELOG.md
app/src/utils/api.test.tsx
app/src/utils/api.ts

Hot fix
- Sets API requests to time out at 14 seconds, instead of 7

Hot fix: Updating timeout

---

CHANGELOG.md
package-lock.json
package.json
public/CHANGELOG.md

No ticket, potentially to fix a file caching issue we're seeing in prod.
- Upgrade next.js.

Next upgrade

---

CHANGELOG.md
__tests__/api/healthcheck/healthcheck.test.tsx
app/api/healthcheck/route.tsx
jest.config.ts

- JIRA ticket [DR-3304](https://newyorkpubliclibrary.atlassian.net/browse/DR-3304)
- Adds `api/healthcheck` endpoint (and one test)
** Needs to be added to RP config, and AWS url needs to be updated, for this work to be complete
Hit `/api/healthcheck` 
[DR-3304]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DR-3304: Health check endpoint

---

app/src/components/results/noResultsFound.tsx
app/src/styles/Collections.module.css

following lily's VQA feedback on the "no results" view of the All Collections page. she approved and this just needs to go off to QA.

vqa fixes for no results page

---

.github/workflows/deploy_qa.yml

- JIRA ticket [xxx](url)
-
-
-

update ecs cluster name for digital-collections QA

---

CHANGELOG.md
__tests__/pages/collectionpage.test.tsx
app/collections/[slug]/page.tsx
app/src/components/pages/collectionPage/collectionPage.tsx
app/src/components/pages/searchPage/searchPage.tsx
app/src/components/search/filters.tsx

- JIRA ticket [DR-3361](https://newyorkpubliclibrary.atlassian.net/browse/DR-3361)
- Adds layout for collection page and a11y page test
[DR-3361]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DR-3361: Skeleton of `collections/:uuid` page

---

app/api/schema/collections/[uuid]/children/route.tsx
app/src/components/pages/collectionsPage/collectionsPage.tsx
app/src/data/schemas/collectionsChildrenSchema.ts
app/src/data/schemas/collectionsSchema.ts
app/src/data/schemas/collectionsUUIDSchema.ts
app/src/data/schemas/searchSchema.ts

- JIRA ticket [DR-3395](https://newyorkpubliclibrary.atlassian.net/browse/DR-3395)
- Creates the `collections/:uuid`, `collections/:uuid/children` schema for Collections API 
- Creates corresponding endpoints
DCFL page mapped to Collection API endpoint mapped to component:
[DR-3395]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DR-3395: `collections/:uuid` schema

---

CHANGELOG.md
app/layout.tsx

- JIRA ticket [DR-3376](https://newyorkpubliclibrary.atlassian.net/browse/DR-3376)
- Adds explicit `strategy` prop to all of our 3rd party scripts, to optimize TBT
This is difficult to test, since the DevTools Lighthouse reports don't return consistent results (not to mention, it looks like we have fantastic TBT when I run those reports on prod). Based off common sense alone, these are the strategy settings I would use, and they don't seem to *negatively* affect TBT... but they're also not consistently improving it. What else can I do to test these settings ?
[DR-3376]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DR-3376: Optimize third party scripts

---

.github/workflows/deploy_production.yml
.github/workflows/deploy_qa.yml

that would do it

---

app/src/config/constants.ts
app/src/utils/searchManager/searchManager.tsx

Add a couple more subject types (ie temporal and occupation) and a filter for notes.
- JIRA ticket [DR-xxxx](url)

Allow more search filters

---

CHANGELOG.md
app/src/components/items/react/player.tsx
app/src/components/items/viewer/viewer.tsx
app/src/models/item.ts
package-lock.json
package.json

replace UV with https://github.com/cookpete/react-player?tab=readme-ov-file#supported-media for AV

No ref/reactplayer

---

app/items/[uuid]/page.tsx
app/src/components/items/viewer/fallback.tsx
app/src/models/item.ts

- use Permitted Locations field from manifest to populate banner for restricted Items
- update GA4 data

use new permitted location field in manifest

---

CHANGELOG.md
app/src/components/search/filters/filters.tsx
playwright/pages/search.page.ts

Just fixing a grammatical issue that bugs me.

[NO-REF] Change less to fewer because I am that guy.

---

app/src/components/items/overview/external/overview.tsx

- JIRA ticket [
DR-3781 Update copy: catalog and archive buttons on item page](https://newyorkpubliclibrary.atlassian.net/browse/DR-3781)
changes "view this item elsewhere" to "data source:" or "data sources:"
lana and I tested this: 
plural: https://digital-collections-git-dr-3781-update-copy-catalog-ae2164-nypl.vercel.app/items/6fa3b180-fc7d-0139-3ccc-0242ac110003?canvasIndex=0
singular: https://digital-collections-git-dr-3781-update-copy-catalog-ae2164-nypl.vercel.app/items/e6574800-c551-012f-ee1f-58d385a7bc34?canvasIndex=0

update copy from "View this item elsewhere" to "Data source" or "Data sources"

---

app/src/components/items/plyr/dynamic.tsx
app/src/components/items/plyr/player.tsx
app/src/components/items/viewer/viewer.tsx

make the Plyr AV component dynamic to solve the webpack "document is not defined" error seen in the console

make the plyr player component dynamic

---

app/src/components/pageLayout/pageLayout.tsx
playwright/tests/items-landing.spec.ts

Remove site issue banner

---

CHANGELOG.md

Release 0.4.7

---

CHANGELOG.md
package-lock.json
playwright/pages/search.page.ts
playwright/tests/search.spec.ts

- JIRA ticket [DR-DR3796](url)
Adds Name filter to search-tests.
I'm going through the filters section of the search tests and adding the remaining filters from the initial implementation.  When all 8 filters have been added to the test, this work should be ready to merge.  Date and Availability filters will be done in a separate ticket.
Run search test, or just the filters section, with playwright.
- [ x] All new and existing tests passed.

Added a Name filter selection to search-tests
