- CHANGELOG.md
- package-lock.json
- package.json
- updates version of  NYPL Reservoir to 2.0.1
- ran `npm install` and then `npm run dev` locally and checked if the app loaded by hitting http://localhost:3000/
> update reservoir version to 2.0.1

- docker-compose.yml
- removes volumes from the docker-compose.yml file (reason being because running `docker-compose build` moves the /pages and /styles directory to the root, which would be fine if they didn't already exist in the /src directory)
- running `docker-compose build` and `docker-compose up` locally and hitting localhost:3000 works
- running `docker-compose build` and `docker-compose up` locally does not create a /pages or /styles directory at the root level
> remove volumes from docker-compose.yml

- CHANGELOG.md
- README.md
- src/components/hero/campaignHero.tsx
- src/components/hero/campaignHeroHeading.tsx
- src/components/hero/campaignHeroSubText.tsx
- src/pages/index.tsx
- src/utils/utils.test.tsx
- src/utils/utils.ts
- JIRA ticket [DR-2543](https://jira.nypl.org/browse/DR-2543)
- Display the total number of available digitized items on DC
- Should display within the hero title
- Use the same typography as the rest of the title
- Updates on a regular schedule (dev can suggest the best cadence and update this)
- Should include location restricted materials as well as the ones available anywhere
-
> DR-2543/campaign hero number of digitized items

- src/components/notificationBanner/notificationBanner.tsx
- src/pages/index.tsx
Fixes JIRA ticket [DR-2583](https://jira.nypl.org/browse/DR-2583).
- Adds the notification banner directing users to old DC site
> DR-2583 Notification banner

- src/pages/_app.tsx
Fixes JIRA ticket [DR-2741](https://jira.nypl.org/browse/DR-2741).
- Adds meta title and description tags
- Adds OG tags for sharing
- Adds Twitter tags for sharing
Locally, [Vercel Open Graph preview](https://vercel.com/nypl/digital-collections/Cyb6K88Zbjg9sLwJRifAjyEsr6V9/og)
> DR-2741: Add meta and OG tags to head

- CHANGELOG.md
- src/components/hero/campaignHero.tsx
- src/components/homePageMainContent/homePageMainContent.tsx
- src/pages/api/featuredItem.ts
- src/pages/api/homepage.ts
- src/utils/utils.ts
- JIRA ticket [DR-2814](https://jira.nypl.org/browse/DR-2814)
- This adds caching for 24hours to the Next.js internal API routes for `/api/featuredItem` and `/api/homepage`.
- These two endpoints are hit by the client through fetch calls. I'm using the `{ cache: "force-cache" }` option which will always use the cache if available unless a hard refresh is made. This is based on the docs but I'm wondering if it is too aggresive. https://developer.mozilla.org/en-US/docs/Web/API/Request/cache
- The [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) is a browser API but node also supports it. I don't think it's right to aggressively cache the fetch call to Repo API but would it make sense to do so?
Locally.
- N/A
> DR-2814: Adding api route caching and client side fetch call caching

- src/utils/utils.ts
- None
- Updates the `imageURL` of the utils file to grab the `IIIF_URL` setting from app config instead of `.env`, thus making use of the changes added in #85:
- Vercel app now successfully displays images (whereas they were previously showing blank values):
- **Before:**
- **After:** 
- None
> Read IIIF_URL setting from app config file instead of .env

- .env.example
- src/components/hero/hero.test.tsx
- src/components/homePageMainContent/homePageMainContent.test.tsx
- src/pages/api/homepage.ts
- src/utils/utils.test.tsx
- src/utils/utils.ts
- JIRA ticket [DR-2824](https://jira.nypl.org/browse/DR-2824)
- This removes the code that queued up 28 API calls to Repo API for the item number count for each collection.
- The current behavior is to make an array of all the uuids and hit the new `/items/counts` Repo API endpoint to get all the item number count in one request.
- The relevant code has been updated.
Locally with both QA and prod Repo API.
- N/A
> DR-2824: Repo API endpoint for uuids to item count response

- src/components/exploreFurther/exploreFurther.tsx
Resolves JIRA ticket [DR-2834](https://jira.nypl.org/browse/DR-2834).
- Adds hover underline to Explore further links
- **This requires some overriding of the Link styles (instead of just using the default card heading behavior, as seen in the swim lanes) because the links need to open in a new tab
Locally
> DR-2834: Explore further link hover

- src/components/hero/campaignHeroSubText.tsx
Resolves JIRA ticket [DR-2833](https://jira.nypl.org/browse/DR-2833)
- Removes the extra space in the hero's image link
Locally
> DR-2833: Remove extra link space

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- test/homepageImageLoadingTest.js
- test/imageTest5.js
- JIRA ticket [Configure passenger settings for Repo API](https://jira.nypl.org/browse/DR-2872)
- Adds a test script to assert that swim lane images load on the homepage
- Install puppeteer with `npm install puppeteer`
- Get on the VPN and accessinate your IP for nypl-dams-dev
- Run the test against qa with `node test/homepageImageLoadingTest.js`. If it does not time out, that means it succeeded. It should print all images loaded and the time taken for the swim lane images to finish loading, including the 12 that require scrolling down the page. This simulates a single user loading the homepage one time.
- Run the test against production with `node test/homepageImageLoadingTest.js --prod`. The above still applies.
- None
> DR 2872 puppeteer script for facelift homepage

- CHANGELOG.md
- next.config.js
- public/newrelic-browser.js
- src/lib/newrelic/NewRelic.tsx
- src/pages/_app.tsx
- src/types/globals.d.ts
This adds a NewRelic snippet to every page to enable client-side monitoring.
Mostly follows the pattern set by the DRB team, with some small changes to not require the license key to be committed to the repository: https://github.com/NYPL/sfr-bookfinder-front-end/blob/9d7f9060d00e8b345047bd7605b75d953cef73c2/src/lib/newrelic/NewRelic.tsx
Currently this is not working due to a CORS issue when connecting to NewRelic!
> DR-2893 add NewRelic client side monitoring

- .github/workflows/swimlanes_test.yml
- CHANGELOG.md
- package.json
- test/homepageFeaturedImageLoadingTest.js
- JIRA ticket [Create featured image test and have it run with the swimlanes test](https://jira.nypl.org/browse/DR-2915)
- Adds a test script to assert that the featured image loads on the homepage
- Do `npm install`
- Make sure you are accessinated and can reach the facelift qa environment
- Run the test against qa with `npm run homepageFeaturedImageLoadingTestQa`. If it does not time out, that means it succeeded. It should print all images loaded and the time taken, and it should succeed as long as the featured image loads and can be found in the DOM. This simulates a single user loading the homepage one time.
- Run the test against production with `npm run homepageFeaturedImageLoadingTestProd`. The above still applies.
- None
> DR 2915 puppeteer script for facelift homepage featured image

- src/components/header/header.tsx
Resolves JIRA ticket [DR-2913](https://jira.nypl.org/browse/DR-2913).
- Adds bottom border to header on screen sizes less than 767px
Locally
> DS-2913: Header bottom border

- .github/workflows/legacy_swimlanes_test.yml
- CHANGELOG.md
- package.json
- test/legacyHomepageImageLoadingTest.js
- JIRA ticket [Run puppeteer script on legacy Digital Collections for images.nypl.org](https://jira.nypl.org/browse/DR-2921)
- Added a puppeteer script to test the loading of the swimlanes images on the legacy digital collections homepage.
- Added a new GitHub Actions workflow to also make this script run every 10 minutes
- Do `npm install`
- Do `npm run npm run legacyHomepageImageLoadingTestProd`
- The test should run and should (probably) succeed once the 24 images we expect to load have loaded.
- NB: We'll need to wait until the qa homepage is fixed to do anything with the qa site. That can come in a subsequent PR.
- N/A
> DR 2921 Add a test for legacy dc homepage images

- CHANGELOG.md
- src/components/hero/campaignHeroSubText.tsx
- src/components/publicDomainFilter/publicDomainFilter.tsx
- src/data/aboutPageElements.tsx
Resolves JIRA ticket [DR-2936](https://jira.nypl.org/browse/DR-2936)
- Points "Learn more" link in hero to the harmful content section of About page
- Points "What is public domain?" link in header to the public domain/copyright section of About page
Locally
- Anchor links point to the correct place on the page, but often the text they're pointing to is covered by the sticky header. This is expected and will be addressed in [this ticket](https://jira.nypl.org/browse/DR-2911), it is not considered a blocker to launch by Clare
> DR-2936: Point hero and header links to About page

- .github/workflows/swimlanes_test.yml
- CHANGELOG.md
- JIRA ticket [Run swimlanes and featured images test 10 times in parallel during load test](https://jira.nypl.org/browse/DR-2937)
- Makes the featured and swimlanes images scripts run every 2 minutes instead of every 10 minutes
- Makes the same scripts run 10x in parallel for each execution
- Tests not possible until merging to main
- We should:
- Merge during "off hours" and monitor the workflow behavior
- Disable the workflow afterwards
- Rework the workflow if the behavior isn't as described in the ticket. 
- Enable the workflow shortly before the load test
- Disable the workflow shortly after the load test
- N/A
> DR-2937 Run swimlanes and featured images test 10 times in parallel during load test

- .github/workflows/swimlanes_test.yml
- JIRA ticket [Run swimlanes and featured images test 10 times in parallel during load test](https://jira.nypl.org/browse/DR-2937)
- Makes the featured and swimlanes images scripts run every 5 minutes instead of every 2 minutes (5 minutes is the minimum allowed interval since 2019)
- Add the ability to trigger the workflow manually via the GitHub API
- Tests not possible until merging to main
- We should:
- Merge during "off hours" and monitor the workflow behavior
- Disable the workflow afterwards
- Rework the workflow if the behavior isn't as described in the ticket. 
- Enable the workflow shortly before the load test
- Disable the workflow shortly after the load test
- N/A
> DR-2937 Run swimlanes and featured images test 10 times in parallel during load test v2

- .github/workflows/swimlanes_test.yml
- JIRA ticket [Run swimlanes and featured images test 10 times in parallel during load test](https://jira.nypl.org/browse/DR-2937)
- Removes the cron schedule from the swim lanes test workflow to allow for manual triggering only in preparation for tomorrow's load test (we already got a lot of good 10x data from today).
- Tests not possible until merging to main
- N/A
> DR-2937 remove cron from swim lanes test

- CHANGELOG.md
- README.md
- JIRA ticket [DR-2928](https://jira.nypl.org/browse/DR-2928))
- Adds cluster names to the readme
> DR-2928 add cluster names to readme

- CHANGELOG.md
- src/data/aboutPageElements.tsx
Resolves JIRA ticket [DR-2972](https://jira.nypl.org/browse/DR-2972).
- Removes 2nd paragraph from Linked Projects section
- Replaces paragraph in Platforms section
- Changes non-NYPL links on About page to open to new tab
> DR-2972: Text edits to About page

- src/components/exploreFurther/exploreFurther.tsx
- src/components/featuredContent/featuredContent.test.tsx
- src/components/featuredContent/featuredContent.tsx
- src/components/hero/campaignHero.tsx
- src/components/swimlanes/swimLanes.tsx
- src/data/featuredContentData.ts
- src/pages/api/homepage.ts
- JIRA ticket [Fallback image for Featured Item](https://jira.nypl.org/browse/DR-2925)
- JIRA ticket [Update DS version on DC Facelift to v3.0](https://jira.nypl.org/browse/DR-2924)
comparing https://digital-collections-git-release-018-nypl.vercel.app/  to https://new-digitalcollections.nypl.org/, this PR:
- updates the "see more" links in the swim lanes to be blue (instead of black) and display a dotted line (instead of a solid line).
- updates the links in the "Explore Further" card title to have a visited state after clicking.
locally
- 
- the "see more" links - I am having issues adding some padding/a margin to the dotted line below the links on hover to match the style that exists on prod.
> No ref/bug fixes

- src/components/hero/campaignHeroSubText.tsx
- JIRA ticket [DR-2986](https://jira.nypl.org/browse/DR-2986).
- Adds a non-breaking space between "to" and "view" in the hero's body text.
Locally, test all screen sizes.
> DR-2986: Add word break in hero

- CHANGELOG.md
- app/components/exploreFurther/exploreFurther.tsx
- app/components/swimlanes/swimLanes.tsx
- JIRA ticket [DR-3024](https://newyorkpubliclibrary.atlassian.net/browse/DR-3024)
- makes the whole card clickable by addding `mainActionLink` prop to the Card components rendered  in the `swimLanes` and `exploreFurther` components
-
[DR-3024]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-3024 make entire card clickable

- CHANGELOG.md
- app/collections/[slug]/page.tsx
- app/components/collections/collections.tsx
- app/components/search/body.tsx
- app/components/search/content.tsx
- app/components/search/results.tsx
- app/search/index/page.tsx
- middleware.tsx
- JIRA ticket [DR-3028](https://newyorkpubliclibrary.atlassian.net/browse/DR-3028)
creates url structure for the following pages:
- `/search/index`
- `/collections/[slug]`
also accepts query parameters and renders query param on the body
locally
-
[DR-3028]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-3028 create url structure for phase 3

- CHANGELOG.md
- app/collections/lane/[slug]/page.tsx
- app/src/components/pages/collectionLanePage/collectionLanePage.tsx
Resolves ticket [DR-3106](https://newyorkpubliclibrary.atlassian.net/browse/DR-3106)
- Renders the swimlane landing page with dummy data
Locally: ex `/collections/lane/hello`
[DR-3106]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-3106: Render collection swimlane page

- CHANGELOG.md
- middleware.tsx
- JIRA ticket https://newyorkpubliclibrary.atlassian.net/browse/DR-3122
- adds qa environment to middleware to prevent redirects to phase 2-4 pages from redirecting to the homepage in the qa environment
locally by updating APP_ENV in .env.local to "qa" and trying to hit http://localhost:3000/divisions/test-collections-1
-
> DR-3122 add qa to middleware

- CHANGELOG.md
- __tests__/pages/notfoundpage.test.tsx
- app/not-found.tsx
- app/src/components/pageLayout/pageLayout.tsx
- app/src/components/pages/notFoundPage/notFoundPage.tsx
- JIRA ticket [DR-3168](https://newyorkpubliclibrary.atlassian.net/browse/DR-3168)
- Adds `not-found.tsx` file and `notFoundPage` client component
- Adds test
- The test I wrote isn't truly end to end but that's the coverage Research Catalog has. Wondering if we should look into Cypress or something since Jest on its own is not great for this
- Designers have a universal 404/error page design in the works, so this may have visual updates soon
Hit `/404`
[DR-3168]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-3168: 404/Not found page

- app/src/components/grids/collectionsGrid.tsx
- JIRA ticket [DR-3098](https://newyorkpubliclibrary.atlassian.net/browse/DR-3098)
- following Clare's feedback in https://docs.google.com/document/d/1aFNbdvedpTXfT6CVKBXZKMj71SXdhuP_CPepqUlAY8o/edit, tab index of the header should be -1
-
-
[DR-3098]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> tab index should be -1 for non interactive elements

- CHANGELOG.md
- app/layout.tsx
Resolves JIRA ticket [DR-3264](https://newyorkpubliclibrary.atlassian.net/browse/DR-3264)
- Removes canonical url for old DC in anticipation of reverse proxy launch
- Check `<head>`
[DR-3264]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-3264: Remove canonical tag linking to old DC

- app/src/components/card/card.tsx
N/A, hot fix
- Fixes the issue of images not re-rendering on pagination by adding `key` to the `Card`
> No ref: Add unique key so images re-render on Card

- CHANGELOG.md
- app/src/components/pages/divisionPage/divisionPage.tsx
- public/CHANGELOG.md
- JIRA ticket [DR-3274](https://newyorkpubliclibrary.atlassian.net/browse/DR-3274)
- uses the data returned from repo api for the title and breadcrumb data instead of the slug
- Lana mentioned the title gets cut off but I only see that in the breadcrumb? am I missing something?
locally
-
[DR-3274]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix division title on division landing pages

- CHANGELOG.md
- app/collections/[slug]/page.tsx
- app/collections/lane/[slug]/page.tsx
- app/collections/page.tsx
- app/divisions/[slug]/page.tsx
- app/divisions/page.tsx
- app/items/[uuid]/page.tsx
- public/CHANGELOG.md
Resolves JIRA ticket [DR-3273](https://newyorkpubliclibrary.atlassian.net/browse/DR-3273)
- Adds specific Open Graph title tags to metadata, so that shared pages have their own title instead of the generic "NYPL Digital Collections"
Check the `<head>` on a page with a slug
[DR-3273]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-3273: Optimize Open Graph title tags

- app/src/models/collectionCard.ts
- JIRA ticket [DR-3288)](https://newyorkpubliclibrary.atlassian.net/browse/DR-3288)
- uses the URL returned by Repo API instead of the title to generate the card links
- The url was using the title in only dev and qa, I remember setting this for the interal linking changing. Good thing we caught this now. 
- decided to use '.replace("https://digitalcollections.nypl.org",'') to return the path of the url to avoid breaking the links in the RP.
Locally to make sure the links generate correctly (don't have multiple ''//' or 'digitalcollections.nypl.org'). However, this needs to be and can really only be formally be tested in QA.
-
> hotfix to fix the collection card urls

- app/src/models/itemCard.ts
- Updates the url on item cards to be exclusively the uuid, rather than the `href` or `url`. This helps us debug since we are only expecting one thing and it's not environment dependent
> Hot fix: Item cards use uuid urls

- .github/workflows/deploy_production.yml
- CHANGELOG.md
- package-lock.json
- package.json
- Updates prod cluster name to `new-digitalcollections-prod`
- Fixes changelog and versioning from day of weird releases
> Hot fix: Updating GHA prod cluster name

- .github/workflows/deploy_production.yml
- CHANGELOG.md
- package-lock.json
- package.json
- Updated collection card urls to use uuid
- Moved `/divisions` and `/divisions/[slug]` from behind middleware, now accessible
- Updated item card urls to use uuid
- Updated collection card urls to use legacy url
- **Updated prod ECS cluster name to `new-digitalcollections-prod`**
> Release 0.1.19 (again...)

- app/src/models/collectionCard.ts
- Hardcodes collection card urls to go back to legacy DC
> Hot fix: Rewinding collection links

- CHANGELOG.md
- app/src/components/pages/divisionsPage/divisionsPage.tsx
- app/src/utils/api.ts
- app/src/utils/itemCount.test.tsx
- app/src/utils/itemCount.ts
- JIRA ticket [DR-3297](https://newyorkpubliclibrary.atlassian.net/browse/DR-3297)
- Adds new `getItemsCountFromCollections()` which hits `/collections/{uuid}`  to get `numItems` for each passed `uuid` (really only a helper for `getHomePageData`)
- NOTE: this is declared and tested in a separate file because of Jest mocking conventions. When I get to this https://newyorkpubliclibrary.atlassian.net/browse/DR-3271 I'll refactor all of the API helper tests and it'll be less weird
Go to the homepage and think to yourself, is this slower than usual 
[DR-3297]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-3297: Rewrite getHomePageData to no longer use `items/counts`

- .env.example
- CHANGELOG.md
- JIRA ticket [DR-2794](https://newyorkpubliclibrary.atlassian.net/browse/DR-2794)
- Updates the credentials the app uses for Google Sheets API: **GET NEW ENVIRONMENT VARS FROM ME** 
- Also corrects the `env.example`– there are some variables in there that are not actually used for the Google Sheets access or anything
Get the new vars, then run it locally, enter feedback, check that the email updating the form is `dc-feedback@dc-facelift-feedback.iam.gserviceaccount.com` (not `digital-collections@digital-collections-408515.iam.gserviceaccount.com`).
[DR-2794]: https://newyorkpubliclibrary.atlassian.net/browse/DR-2794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-2794: New feedback form credentials 

- CHANGELOG.md
- app/src/utils/fetchApi.test.tsx
- app/src/utils/fetchApi.ts
- JIRA ticket [DR-3297](https://newyorkpubliclibrary.atlassian.net/browse/DR-3297)
- Brings Repo API request timeout down to 10 seconds from 14
- This is with team input– general discomfort with it being lower than 10, given New Relic average response times
[DR-3297]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-3297: Restore timeout for Repo API requests 

- CHANGELOG.md
- app/src/components/header/header.tsx
- JIRA ticket [DR-3322](https://newyorkpubliclibrary.atlassian.net/browse/DR-3322)
- Adjusts header behavior so that it expands to show nav links on scroll up on tablet/desktop (previously only did this on mobile)
Scroll down and then up :)
- Don't think this needs to be flagged since this behavior is already approved on mobile
[DR-3322]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-3322: Expand desktop nav on scroll

- CHANGELOG.md
- __tests__/pages/collectionspage.test.tsx
- app/src/components/pageLayout/pageLayout.tsx
- app/src/components/pages/collectionsPage/collectionsPage.tsx
- app/src/config/constants.ts
- public/CHANGELOG.md
- JIRA ticket [include "sort by" label inside the drop down](https://newyorkpubliclibrary.atlassian.net/browse/DR-3323)
-
-
-
> update label text on sort menu for all collections page

- CHANGELOG.md
- app/collections/page.tsx
- JIRA ticket [DR-3357](https://newyorkpubliclibrary.atlassian.net/browse/DR-3357)
- 404 redirect was incorrectly checking that the message was NOT "No collections found", now fixed
[DR-3357]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-3357: Correcting `/collections` 404

- CHANGELOG.md
- app/collections/page.tsx
- app/src/components/pages/collectionsPage/collectionsPage.tsx
- app/src/components/results/noResultsFound.tsx
- JIRA ticket [DR-3357](https://newyorkpubliclibrary.atlassian.net/browse/DR-3357)
- Updates `/collections` "no results" to handle edge cases that return 404s
- Necessary bc Repo API doesn't differentiate between a page number out of bounds 404 and a keyword no results 404
** By "invalid keyword" below, I mean a keyword that returns no results.
A search with invalid keyword, no page number = "No results for '[keyword]'":
https://digital-collections-git-dr-3357-correcting-collections-404-nypl.vercel.app/collections?collection_keywords=hello
A search with no keyword, invalid page number = "No results":
https://digital-collections-git-dr-3357-correcting-collections-404-nypl.vercel.app/collections?page=9000
A search with valid keyword, invalid page number = "No results for '[keyword]' found …
> DR-3357 (pt 2): Collections "no results" edge cases

- CHANGELOG.md
- app/src/components/featuredContent/featuredContent.test.tsx
- app/src/data/featuredContentData.ts
- JIRA ticket [DR-3378](https://newyorkpubliclibrary.atlassian.net/browse/DR-3378)
- Corrects link to page on public domain resources from the `FeaturedContent` on homepage
[DR-3378]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-3378: Public domain link correction

- .github/workflows/deploy_qa.yml
- CHANGELOG.md
- app/src/components/featuredContent/featuredContent.test.tsx
- app/src/data/featuredContentData.ts
- middleware.tsx
- package-lock.json
- package.json
- Public domain link correction (DR-3378)
- Updated middleware to no longer include `/collections` and `collections/lane/:slug`
- Updated QA cluster name
> Release 0.3.0

- CHANGELOG.md
- app/collections/page.tsx
- app/src/components/pages/collectionsPage/collectionsPage.tsx
- app/src/components/search/dcSearchBar.tsx
- app/src/components/search/search.test.tsx
- app/src/components/search/search.tsx
n/a
Should be merged in with [DR-3365](https://github.com/NYPL/digital-collections/pull/286) since it corrects the loading
- Replicates the DS `Searchbar` component but pared down to what DC uses, specifically getting rid of the `<form>` wrapper, which was triggering extra search submits
- Added `maxWidth` as a prop since that's something we have been overriding but not everywhere
- Generally, is it okay to have removed so much of the `Searchbar`? Wanted to keep what we actually use (and will use in the foreseeable future), so for example I removed the entire `select` element and all its corresponding props.
- Is it okay to add the "Enter" keyboard behavior back in (see comment)?
`search.test.tsx` tests should still cover this, and it should look and work exactly the same as before
- Want …
> No ref: DC custom search bar

- CHANGELOG.md
- __tests__/middleware/redirect.test.tsx
- app/collections/page.tsx
- app/src/components/pages/collectionsPage/collectionsPage.tsx
- app/src/types/CollectionSearchParams.ts
- app/src/utils/searchManager.test.tsx
- app/src/utils/searchManager.tsx
- middleware.ts
- next.config.js
- public/CHANGELOG.md
- tsconfig.json
- JIRA ticket [DR-3337](https://newyorkpubliclibrary.atlassian.net/browse/DR-3337)
- Replaces `collection_keywords` with `q` in the collection search params
- Adds a 301 redirect so that bookmarked URLs with `collection_keywords` go to `q`
- Tests the above
Try to hit `/collections?collection_keywords=something` and watch the magic unfold (also try with a sort or a page number applied as well)
[DR-3337]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-3337: `collection_keywords` redirect

- app/src/data/schemas/CHANGELOG.md
- app/src/data/schemas/collectionsUUIDSchema.ts
- app/src/data/schemas/searchSchema.ts
- n/a
- Adds `donorCredit` field to `collections/:uuid`schema
- Removes "PDF" as an option for `contentType` on `search` schema
- Updates schema changelog in general
> No ref: `/search` and `collections/:uuid` schema corrections

- CHANGELOG.md
- __tests__/pages/collectionpage.test.tsx
- __tests__/pages/collectionspage.test.tsx
- __tests__/pages/searchpage.test.tsx
- app/collections/[slug]/page.tsx
- app/collections/page.tsx
- app/src/components/pages/collectionPage/collectionPage.tsx
- app/src/components/pages/collectionsPage/collectionsPage.tsx
- app/src/components/pages/searchPage/searchPage.tsx
- app/src/components/sortMenu/sortMenu.test.tsx
- app/src/components/sortMenu/sortMenu.tsx
- app/src/config/constants.ts
- app/src/context/SearchProvider.tsx
- app/src/utils/apiClients.tsx
- app/src/utils/searchManager.test.tsx
- app/src/utils/searchManager.tsx
- JIRA ticket [DR-3366](https://newyorkpubliclibrary.atlassian.net/browse/DR-3366)
- Creates the `SortMenu` component and replaces/places it on pages with sort
-  Adds a `SearchManager` instance to `/collections/[slug]` page (already exists on `/search`, `/collections`) so sort can be updated via URL
Click around the sort menu on `/collections/[slug]`, `search`, and `/collections`- check the URL updates as expected
[DR-3366]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-3366: Sort component

- CHANGELOG.md
- __tests__/pages/collectionpage.test.tsx
- app/src/components/pages/collectionPage/collectionPage.tsx
- app/src/components/pages/searchPage/searchPage.tsx
- app/src/components/search/filters/activeFilters.test.tsx
- app/src/components/search/filters/activeFilters.tsx
- app/src/components/search/filters/selectFilter.test.tsx
- app/src/components/search/filters/selectFilter.tsx
- app/src/components/search/filters/selectFilterGrid.test.tsx
- app/src/context/SearchProvider.tsx
- app/src/utils/searchManager.test.tsx
- app/src/utils/searchManager.tsx
- JIRA ticket [DR-3367](https://newyorkpubliclibrary.atlassian.net/browse/DR-3367)
- Creates `activeFilters` component with `TagSet` and adds it to `/search` and `/collections/[slug]`
- Adds/updates filter management in `searchManager`
Add and remove filters etc. Complete filter modal is not in this branch but dropdowns should work enough to show how the `TagSet` / `SearchManager`/ URL communication work
[DR-3367]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-3367: Active filters 

- app/src/components/publicDomainFilter/publicDomainFilter.tsx
- JIRA ticket [DR-3523](https://newyorkpubliclibrary.atlassian.net/browse/DR-3523)
- Separates the public domain checkbox label from the `Checkbox` into its own element so that the click behavior can be overridden so that the layout doesn't shift on click so that the header doesn't jump :)
[DR-3523]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-3523: Header shift bug (pt 2)

- __tests__/middleware/collectionRedirects.test.tsx
- __tests__/middleware/searchRedirects.test.tsx
- app/src/config/constants.ts
- app/src/utils/fetchApi.ts
- app/src/utils/searchManager.tsx
- middleware.ts
- tsconfig.json
- Handles _filter_ redirects within the search query, so that links to filters from the item page (ex. [item with physical description link](https://digitalcollections.nypl.org/items/c7438e90-ebed-013d-3ecf-0242ac110002)) as well as bookmarked filters on a search query will work
- See [this doc](https://docs.google.com/document/d/1_HDSzW5ToWf6ariAm7G0VWoUTvPBCqbq7q-9gInqQiM/edit?tab=t.0#heading=h.1ku3d96grql6) again for all the expected redirects and example URLs
- Lana has confirmed that for filters that do not appear as dropdowns on our new search page (namely physical description/form and language) the tag appearing in the "Applied filters:" is sufficient to indicate that you are filtering with that value, even if the dropdown isn't visible/selected
- Similar work will need to be done …
> No ref: Search filter redirects

- CHANGELOG.md
- __tests__/pages/notfoundpage.test.tsx
- app/src/components/pages/notFoundPage/notFoundPage.tsx
- public/CHANGELOG.md
- JIRA ticket [DR-3550](https://newyorkpubliclibrary.atlassian.net/browse/DR-3550)
- Adds client-side logs to see the path that resulted in the 404 not found page.
- Logs this to New Relic.
- N/A
Will test on QA NR.
- N/A
[DR-3550]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-3550: add logs to 404 to New Relic

- CHANGELOG.md
- app/src/utils/utils.test.tsx
- app/src/utils/utils.ts
- JIRA ticket [DR-3564](https://newyorkpubliclibrary.atlassian.net/browse/DR-3564)
- Encodes the search query filters, so that any and all special characters are encoded by the time they hit Solr
** Keyword was recently encoded in a previous PR
- Resolves bug we were noticing where filters with values containing ampersands would return no results: try `q=maps` and then selecting "G.W. Bromley & Co" under the "Name" filter. Previously, this returned 0 results, now it should correctly return ~2551
[DR-3564]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-3564: Encode filter values

- CHANGELOG.md
- app/src/components/search/filters/selectFilter.tsx
- JIRA ticket [DR-3598](https://newyorkpubliclibrary.atlassian.net/browse/DR-3598)
- If a dropdown filter has a selection, it does not display any of the other options
- This is because those other filter options (and their corresponding counts) are pretty much meaningless in the context of a search query that enforces one value per filter category. To get the filter option counts as if the current filter selection is not applied (an OR filter) we would need to revamp the backend of search which we are not gonna do rn
[DR-3598]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-3598: Filter count display bug

- CHANGELOG.md
- app/collections/[uuid]/page.tsx
- app/src/components/collectionStructure/collectionStructure.test.tsx
- app/src/components/collectionStructure/collectionStructure.tsx
- app/src/components/pages/collectionPage/collectionPage.tsx
- app/src/components/pages/collectionsPage/collectionsPage.tsx
- app/src/components/pages/searchPage/searchPage.tsx
- app/src/components/search/collectionSearch.tsx
- app/src/components/search/filters/activeFilters.test.tsx
- app/src/components/search/filters/selectFilter.test.tsx
- app/src/components/search/filters/selectFilterGrid.test.tsx
- app/src/components/search/filters/selectFilterModal.test.tsx
- app/src/components/sortMenu/sortMenu.test.tsx
- app/src/components/sortMenu/sortMenu.tsx
- app/src/config/constants.ts
- app/src/context/SearchProvider.tsx
- app/src/utils/searchManager.test.tsx
- app/src/utils/searchManager.tsx
- JIRA ticket [DR-3609](https://newyorkpubliclibrary.atlassian.net/browse/DR-3609)
- Reworks `searchManager` class so that instances can set their own default sort
- Applies change everywhere `searchManager` is used
- Updates `SortMenu` to take sort from results rather than search manager
Confirm that "sequence" is the default sort on the collection landing page (except for keyword searches), and that "relevance" is still the default sort for search.
[DR-3609]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-3609: Adding sequence sort

- CHANGELOG.md
- app/src/components/card/searchCard.tsx
- app/src/utils/utils.test.tsx
- app/src/utils/utils.ts
- Post search release, realized highlights are not returning full title field
- Updates the construction of the title on the search card to use full title field + highlights instead of just highlights
> Hot fix: highlight adjustment

- app/src/components/items/item.tsx
- app/src/components/items/overview/metadata/overview.tsx
- app/src/components/items/viewer/fallback.tsx
- app/src/models/item.ts
- JIRA ticket [Conditionally render media viewer based on rights logic](https://newyorkpubliclibrary.atlassian.net/browse/DR-3645)
- builds a new component `ItemMediaViewerFallback` to handle what should render in place of the Universal Viewer when an Item is restricted OR when a manifest has metadata and no items in the items array.
- divisions links.... currently I'm using the division information returned in the metadata under Library Locations but I'm pretty sure this links to a division in DCFL and not the division link on nypl.org.... Lana wants the banner to include the link to the division on the nypl.org site. I didn't include this logic in this PR but think I'll need to make an object in DCFL that maps DCFL slugs to NYPL Division urls.
locally with this uuid: …
> create component for available on site materials

- app/src/config/constants.ts
- app/src/utils/searchManager/searchManager.tsx
Looks like if this isn't set, the filter will not be included in the API request.  Also, made sure to exclude it from the selectable options, so it doesn't appear as a selectable filter (or should we just include it?)
- JIRA ticket [DR-3640](https://newyorkpubliclibrary.atlassian.net/browse/DR-3640)
Looks like if this isn't set, the filter will not be included in the API
request.  Also, made sure to exclude it from the selectable options, so
it doesn't appear as a selectable filter (or should we just include it?)
This is needed to support https://github.com/NYPL/collections-api/pull/137
Ran this locally against the aforementioned backend PR, searched for 'Much Ado About Nothing', clicked on the subject corresponding to the title:
See that it goes to a search with matching results:
(though …
> Add title filter to collections api

- app/src/components/items/overview/citations/overview.tsx
- app/src/components/items/overview/metadata/overview.tsx
- JIRA ticket [DR-xxxx](url)
Add keys to elements in the metadata and citations that are structured in a list.  Note I had to replace a couple instances of `<>` fragment syntax in favor of the explicit `<Fragment` to pass in a key prop.
This fixes *most* warnings for missing / duplicate keys - there are some edge cases I've seen that are a bit tricky for me, and would have to take more investigation
Opened an item page locally and verified the warnings go away
> fix: Add keys to list elements

- CHANGELOG.md
- playwright.config.ts
- playwright/pages/search.page.ts
- playwright/tests/search.spec.ts
- JIRA ticket [DR-3659](https://newyorkpubliclibrary.atlassian.net/browse/DR-3659)
- Filters search results by one of the first row drop-down filters and by one of the second row drop-down filters
- Confirmed all tests pass on Chromium, but they may be flaky on Firefox and Webkit
Run `npm run playwright`
N/A
[DR-3659]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-3659: Playwright tests to filter search results

- app/items/[uuid]/page.tsx
- app/src/models/item.ts
- JIRA ticket [DR-3587](https://newyorkpubliclibrary.atlassian.net/browse/DR-3587)
Simply add the ga4 data to the PageLayout for the items page. Note, I added some extra logic to extract the subcollection name, using the last collection in the collection list, as that will be the 'immediate' parent
[DR-3587]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add item google analytics pageview events

- app/items/[uuid]/page.tsx
- app/src/models/item.ts
- JIRA ticket [DR-3755](https://newyorkpubliclibrary.atlassian.net/browse/DR-3755)
Standalone items are not part of a collection, which has been breaking the breadcrumbs on the items page. Simply don't try to include the collection if there isn't one.
loaded the problematic item https://qa-digitalcollections.nypl.org/manifests/3c070da0-68c2-0135-eea2-6d7976cc435f on localhost:
[DR-3755]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Handle standalone items in breadcrumbs

- CHANGELOG.md
- app/items/[uuid]/page.tsx
- app/src/utils/apiClients/apiClients.tsx
- app/src/utils/fetchApi/fetchApi.ts
- JIRA ticket [DR-3754](https://newyorkpubliclibrary.atlassian.net/browse/DR-3754)
Currently, our server looks for the IP of the user in various headers to determine rights for the user. However, since our fetch requests are all placed on the nextJS server, living in EC2, the IPs for all the requests end up being EC2 IPs, so our rights logic fails.
To fix this, use `next/headers` to inspect the headers of the incoming request and forward the origin IP to the API. I used the following nextJS doc as a guide for this:
https://nextjs.org/docs/14/app/api-reference/functions/headers#ip-address
I kinda need to see what this looks like when it goes through the reverse proxy, so once this is in, I'll inspect the logs and patch on the server side.
[DR-3754]: …
> Forward client IP through fetch

- CHANGELOG.md
- playwright/pages/search.page.ts
- playwright/tests/search.spec.ts
- JIRA ticket [DR-3659](https://newyorkpubliclibrary.atlassian.net/browse/DR-3659)
- Adds tests to filter search results by date and availability
- Reorganizes previous tests
N/A
Run `npm run playwright` or observe Playwright Tests check in PR
N/A
[DR-3659]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DR-3659: Playwright tests to filter by date and availability

- CHANGELOG.md
- app/src/utils/metadata/normalizeItemMetdata.ts
- JIRA ticket [DR-3785](https://newyorkpubliclibrary.atlassian.net/browse/DR-3785)
An easy one that I noticed that was bugging me, that I think I broke in https://github.com/NYPL/collections-api/pull/164
Run this, load http://localhost:3000/items/27e2abb0-81b7-0134-dafd-00505686a51c?canvasIndex=0:
[DR-3785]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Separate notes with line breaks

- CHANGELOG.md
- app/src/config/constants.ts
- app/src/utils/apiClients/collectionsApiClient.test.tsx
- [DR-3681](https://newyorkpubliclibrary.atlassian.net/browse/DR-3681)
Adds the relevance sorting option to the Collections page and makes it the default sort option.
Updated test. Also tested locally
[DR-3681]: https://newyorkpubliclibrary.atlassian.net/browse/DR-3681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Dr 3681/collections relevance sort
